# Fetching the latest node image on alpine linux
FROM node:alpine AS development

# Declaring env
ENV NODE_ENV development


WORKDIR /src


COPY ./package*.json /src 

RUN npm install

COPY . .


CMD ["npm","start]